import 'package:flutter/material.dart';
import 'package:i18n/generated/l10n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // these are generated by the Flutter Intl extension
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              S.of(context).page_home_counter(_counter),
              // 'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
            SizedBox(height: 40),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                FlatButton(
                  child: Text(
                    '🇵🇱',
                    style: TextStyle(fontSize: 36),
                  ),
                  onPressed: () {
                    setState(() {
                      S.load(Locale('pl', 'PL'));
                    });
                  },
                ),
                FlatButton(
                  child: Text(
                    '🇺🇸',
                    style: TextStyle(fontSize: 36),
                  ),
                  onPressed: () {
                    setState(() {
                      S.load(Locale('en', 'US'));
                    });
                  },
                ),
                FlatButton(
                  child: Text(
                    '🇩🇪',
                    style: TextStyle(fontSize: 36),
                  ),
                  onPressed: () {
                    setState(() {
                      S.load(Locale('de', 'DE'));
                    });
                  },
                ),
              ],
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
